import ClientAppWrapper from './ClientAppWrapper';

// Required for 'output: export' with dynamic routes
export function generateStaticParams() {
  return [
    { slug: [] },
    { slug: ['login'] },
    { slug: ['register'] },
    { slug: ['exam'] },
    { slug: ['dashboard'] },
    { slug: ['profile'] },
    { slug: ['settings'] },
    { slug: ['community'] },
    { slug: ['news'] },
    { slug: ['admin'] },
    { slug: ['admin', 'businesses'] },
    { slug: ['admin', 'questions'] },
    { slug: ['admin', 'payments'] },
    { slug: ['admin', 'users'] },
    { slug: ['admin', 'news'] },
    { slug: ['admin', 'community'] },
    { slug: ['admin', 'inbox'] },
    { slug: ['admin', 'settings'] },

    { slug: ['admin', 'legal'] },
    { slug: ['admin', 'rooms'] },
    { slug: ['admin', 'verify-payments'] },
    { slug: ['admin', 'ads'] },
    { slug: ['admin', 'scraper'] },
    { slug: ['admin', 'generator'] },
    { slug: ['admin', 'seasons'] },
    { slug: ['admin', 'exam-sets'] },
    { slug: ['admin', 'animations'] },
    { slug: ['admin', 'animations', 'preview'] },
    { slug: ['admin', 'support'] },
    { slug: ['admin', 'backups'] },
    { slug: ['room'] },
    { slug: ['lobby'] },
    { slug: ['premium-upgrade'] },
    { slug: ['safety'] },
    { slug: ['forgot-password'] },
    { slug: ['reset-password'] },
    { slug: ['business'] },
    { slug: ['business', 'dashboard'] },
    { slug: ['business', 'content'] },
    { slug: ['business', 'inbox'] },
    { slug: ['business', 'create-ad'] },
    { slug: ['business', 'my-ads'] },
    { slug: ['business', 'wallet'] },
    { slug: ['business', 'settings'] },
    { slug: ['business', 'welcome'] },
    { slug: ['auth', 'business', 'register'] },
    { slug: ['auth', 'business', 'login'] },
    { slug: ['learning-center'] },
    { slug: ['profile', 'dashboard'] },
    { slug: ['profile', 'history-overview'] },
    { slug: ['profile', 'history'] },
    { slug: ['profile', 'bookmarks'] },
    { slug: ['profile', 'threads'] },
    { slug: ['profile', 'messages'] },
    { slug: ['profile', 'friends'] },
    { slug: ['profile', 'settings'] },
    { slug: ['pricing'] },
    { slug: ['contact'] },
    { slug: ['policy'] },
    { slug: ['faq'] },
    { slug: ['payment', 'success'] },
    { slug: ['payment', 'cancel'] }
  ];
}

export default function Page() {
  return <ClientAppWrapper />;
}
